version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      docker: latest
    commands:
      - pip install --upgrade pip && pip install aws-sam-cli
  build:
    commands:
      - sam build -t template/template.yaml
  post_build:
    commands:
      - echo building sam package to $S3_BUCKET
      - sam package --s3-bucket $S3_BUCKET --template-file .aws-sam/build/template.yaml --output-template-file template-output.yaml
artifacts:
  files:
    - template*.yaml

